//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pb_TunnelVisualizar.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pb_TunnelVisualizarDatabaseEntities : DbContext
    {
        public pb_TunnelVisualizarDatabaseEntities()
            : base("name=pb_TunnelVisualizarDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data_waterFlow> data_waterFlow { get; set; }
        public virtual DbSet<data_waterLavel> data_waterLavel { get; set; }
        public virtual DbSet<rule> rules { get; set; }
        public virtual DbSet<sensor> sensors { get; set; }
    }
}
